[project]
name = "FakeSMTPd"
version = "2026.7.1.dev0"
description = "SMTP server for testing mail functionality"
readme = "README.md"
authors = [
    { name = "Sebastian Rittau", email = "srittau@rittau.biz" },
]
license = "MIT"
license-files = ["LICENSE"]
keywords = ["SMTP", "mail", "testing"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Communications :: Email :: Mail Transport Agents",
    "Topic :: Software Development :: Testing",
]
requires-python = ">= 3.10"
dependencies = []

[project.scripts]
fakesmtpd = "fakesmtpd.server:main"

[project.urls]
"Homepage" = "https://github.com/srittau/fakesmtpd"
"GitHub" = "https://github.com/srittau/fakesmtpd"
"Issues" = "https://github.com/srittau/fakesmtpd/issues"
"Changes" = "https://github.com/srittau/fakesmtpd/blob/main/CHANGELOG.md"

[dependency-groups]
dev = [
    "mypy >=2.3.0,<2.4.0",
    "pytest >=9.1.1,<10",
    "pytest-mock >=3.6.1",
    "ruff>=0.15.22,<0.17.0",
]

[tool.uv]
exclude-newer = "5 days"

[tool.uv.build-backend]
module-root = ""
module-name = ["fakesmtpd"]

[tool.pytest.ini_options]
python_files = ["test_*/*.py"]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["E", "F", "B", "I"]

[build-system]
requires = ["uv_build>=0.11.2,<0.13"]
build-backend = "uv_build"
