name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v5
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: "**/poetry.lock"
      - name: Install poetry
        run: pip --disable-pip-version-check install -U poetry
      - name: Install Python packages
        run: poetry install
      - name: Lint with ruff
        run: |
          poetry run ruff --version
          poetry run ruff check
      - name: Type check with mypy
        run: |
          poetry run mypy --version
          poetry run mypy fakesmtpd test_fakesmtpd
      - name: Test with pytest
        run: poetry run pytest
