name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11-dev"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: "**/poetry.lock"
      - name: Install poetry
        run: pip --disable-pip-version-check install -U poetry
      - name: Install Python packages
        run: poetry install
      - name: Lint with flake8
        run: |
          poetry run flake8 --version
          poetry run flake8 --show-source --statistics fakesmtpd test_fakesmtpd
      - name: Type check with mypy
        run: |
          poetry run mypy --version
          poetry run mypy fakesmtpd test_fakesmtpd
      - name: Test with pytest
        run: poetry run pytest
