name: Test

on: [push, pull_request]

jobs:
    build:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.7", "3.8", "3.9", "3.10.0-beta.4"]
            fail-fast: false

        steps:
        - uses: actions/checkout@v2
        - name: Install Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install -U pip setuptools
            pip install -r requirements.txt
        - name: Lint with flake8
          run: |
            flake8 --version
            flake8 --show-source --statistics fakesmtpd test_fakesmtpd
        - name: Type check with mypy
          run: |
            mypy --version
            mypy fakesmtpd test_fakesmtpd
        - name: Test with unittest
          run: pytest
